name: Build
on: 
  push:
    branches:
      - main
  pull_request:
    types: closed
    branches: main
    
jobs:
  build:
    name: Build and test
    runs-on: ubuntu-latest
    steps:
    - env:
        EVENT_CONTEXT: ${{ toJSON(github.event) }}
      run: |
        echo $EVENT_CONTEXT
